### PR TITLE
Multiple changes, mainly bug fix for incorrect render of NavigationBar

### PR DESCRIPTION
**Pull request by rahuljiresal**
- The navigation bar was not rendering correctly (gif 1 and gif 2). It has been fixed now (gif 3)

Gif-1
tabbar-2

Gif-2
tabbar

Gif-3
tabbar-correct
- Added a hairline under the navigation bar just like native iOS.
- Fixed problems where syntax issues were encountered because of the ES6 parser in larger projects with a plethora of dependencies. Replaced `const` with `var`, and `import` with `var` to make the parser happy.

### CODE REVIEW

**Comment by DickyT** [comment]
@rahuljiresal awesome! I will take a look tonight!

**Comment by DickyT** [comment]
@rahuljiresal I just merged to the master and finished some bug fix. You forget to update the navigation bar title while switching the tabbar lol

**Comment by rahuljiresal** [comment]
Oops! Thanks for the fix. This has been a great package! Solved a lot of my problems.
I do have a couple of more changes, will submit them tonight.

**Comment by DickyT** [comment]
prefect, just make sure pull the latest code before you make any changes, or it will be hard to merge.

**Pull request merged**
